
server:
  port: 8081
orika:
  map-nulls: false
config-props:
  first: f
  second: s
  person:
    personNameAndAge: "nameFromProps, 112"
personne:
  personneName: nameFromProps
collections:
  list: "first,second,third"
  list2: "first;second;third"
spring:

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

